;;; init-meow.el --- Meow modal editing configuration -*- lexical-binding: t; -*-


(defun meow-setup ()
  ;;(setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments.
   ;'("1" . meow-digit-argument)
   ;'("2" . meow-digit-argument)
   ;'("3" . meow-digit-argument)
   ;'("4" . meow-digit-argument)
   ;'("5" . meow-digit-argument)
   ;'("6" . meow-digit-argument)
   ;'("7" . meow-digit-argument)
   ;'("8" . meow-digit-argument)
   ;'("9" . meow-digit-argument)
   ;'("0" . meow-digit-argument)
   ;'("/" . meow-keypad-describe-key)
   ;'("?" . meow-cheatsheet))
   )

  (meow-motion-define-key
   '("e" . meow-next)
   '("n" . meow-prev)
   '("s" . meow-left)
   '("t" . meow-right)
   '("<escape>" . ignore)
   )

  (meow-normal-define-key

   '("e" . meow-next)
   '("n" . meow-prev)
   '("s" . meow-left)
   '("t" . meow-right)

   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   ;'("-" . negative-argument)
   ;'("," . meow-inner-of-thing)
   ;'("." . meow-bounds-of-thing)
   ;'("[" . meow-beginning-of-thing)
   ;'("]" . meow-end-of-thing)
   ;'("a" . meow-append)
   '("a" . (lambda () (interactive) (meow-right) (meow-insert)))
   '("A" . (lambda () (interactive) (end-of-line) (meow-insert)))
   ;'("b" . meow-back-word)
   ;'("B" . meow-back-symbol)
   '("c" . meow-change)
   ;'("d" . meow-delete)
   ;'("D" . meow-backward-delete)
   '("d d" . (lambda ()
              (interactive)
              (delete-region (line-beginning-position) (line-end-position))))
   '("C" . (lambda ()
                   (interactive)
                   (kill-line)
                   (meow-insert)))
   ;'("e" . meow-next-word)
   ;'("E" . meow-next-symbol)
   '("f" . meow-find)
   ;'("F" . (lambda () (interactive) (let ((current-prefix-arg -1)) (call-interactively 'meow-find))))
   '("r" . meow-reverse)
   ;'("G" . meow-grab)
   ;'("h" . meow-left)
   ;'("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . (lambda () (interactive) (back-to-indentation) (meow-insert)))
   '("o" . (lambda ()
              (interactive)
              (goto-char (line-end-position))
              (newline)
              (meow--switch-state 'insert)))
   '("O" . meow-open-above)
   ;'("j" . meow-next)
   ;'("J" . meow-next-expand)
   ;'("k" . meow-prev)
   ;'("K" . meow-prev-expand)
   ;'("l" . meow-right)
   ;'("T" . meow-right-expand)
   ;'("m" . meow-join)
   '("S" . (lambda ()
              (interactive)
              (delete-region (line-beginning-position) (line-end-position))
              (meow--switch-state 'insert)))
   '("?" . meow-search)
   ;'("o" . meow-block)
   ;'("O" . meow-to-block)
   ;'("p" . meow-yank)
   ;'("q" . meow-quit)
   ;'("Q" . meow-goto-line)
   ;'("r" . meow-replace)
   ;'("R" . meow-swap-grab)
   ;'("s" . meow-kill)
   ;'("t" . meow-till)
   ;'("u" . meow-undo)
   ;'("U" . meow-undo-in-selection)
   ;'("v" . meow-visit)
   ;'("w" . meow-mark-word)
   ;'("W" . meow-mark-symbol)
   ;'("x" . meow-line)
   ;'("X" . meow-goto-line)
   ;'("y" . meow-save)
   ;'("Y" . meow-sync-grab)
   ;'("z" . meow-pop-selection)
   ;'("'" . repeat)
   '("<escape>" . (lambda ()
                    (interactive)
                    (if meow--selection
                        (meow-cancel-selection)
                      (ignore))))

  )
)

(use-package meow
  :ensure t
  :config
  (meow-setup)
  (meow-global-mode 1))

(provide 'init-meow)
