;;; doom-delcx-teal-theme.el --- Deep teal study dark theme -*- lexical-binding: t; no-byte-compile: t; -*-
;;; Commentary: bg #1A2828  fg #D8D0BC  strings #D0A450  types #90A8C8  control #78C8A8  numbers #C890A0
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-delcx-teal
  "A cool dark theme with deep teal shadows and warm highlights."
  :family 'doom-delcx-teal
  :background-mode 'dark

  ;; name        gui           256           16
  ((bg          '("#1A2828"    "#1A2828"     nil))
   (bg-alt      '("#253535"    "#253535"     nil))
   (base0       '("#0E1818"    "#0E1818"     nil))
   (base1       '("#1A2828"    "#1A2828"     nil))
   (base2       '("#253535"    "#253535"     nil))
   (base3       '("#344444"    "#344444"     nil))
   (base4       '("#455555"    "#455555"     nil))
   (base5       '("#596868"    "#596868"     nil))
   (base6       '("#6E7C7C"    "#6E7C7C"     nil))
   (base7       '("#AAAAAA"    "#AAAAAA"     nil))
   (base8       '("#D8D0BC"    "#D8D0BC"     nil))
   (fg          '("#D8D0BC"    "#D8D0BC"     nil))
   (fg-alt      '("#B0A898"    "#B0A898"     nil))

   (grey        '("#6E7C7C"    "#6E7C7C"     nil))
   (red         '("#C890A0"    "#C890A0"     nil))
   (orange      '("#D0A450"    "#D0A450"     nil))
   (yellow      '("#D0A450"    "#D0A450"     nil))
   (dark-yellow '("#A88040"    "#A88040"     nil))
   (green       '("#78C8A8"    "#78C8A8"     nil))
   (dark-green  '("#58A888"    "#58A888"     nil))
   (teal        '("#78C8A8"    "#78C8A8"     nil))
   (blue        '("#90A8C8"    "#90A8C8"     nil))
   (dark-blue   '("#7088A8"    "#7088A8"     nil))
   (cyan        '("#78C8A8"    "#78C8A8"     nil))
   (dark-cyan   '("#58A888"    "#58A888"     nil))
   (magenta     '("#C890A0"    "#C890A0"     nil))
   (violet      '("#D8A8B8"    "#D8A8B8"     nil))

   (highlight      green)
   (vertical-bar   base4)
   (selection      base4)
   (builtin        blue)
   (comments       base6)
   (doc-comments   base6)
   (constants      magenta)
   (functions      fg)
   (keywords       green)
   (methods        fg)
   (operators      fg)
   (type           blue)
   (strings        orange)
   (variables      fg)
   (numbers        magenta)
   (region         base4)
   (error          red)
   (warning        yellow)
   (success        green)

   (vc-modified    (doom-darken blue  0.15))
   (vc-added       (doom-darken green 0.15))
   (vc-deleted     (doom-darken red   0.15))

   (modeline-bg            base3)
   (modeline-fg            fg)
   (modeline-inactive-bg   bg)
   (modeline-inactive-fg   base6))

  ((cursor :background "white")
   (hl-line :background base3)
   ((line-number &override)              :foreground base5)
   ((line-number-current-line &override) :background base3 :foreground yellow)
   (isearch        :foreground base0 :background orange)
   (lazy-highlight :background base4 :foreground fg :bold bold)
   ((link &override) :foreground blue :underline t)
   (minibuffer-prompt :foreground green)
   (mode-line          :background base3 :foreground modeline-fg)
   (mode-line-inactive :background bg    :foreground modeline-inactive-fg)
   (show-paren-match :background base4 :foreground fg :bold t)
   (company-tooltip            :background base3 :foreground fg)
   (company-tooltip-selection  :background base4)
   (company-tooltip-common     :foreground green)
   (company-tooltip-annotation :foreground base6)
   (company-scrollbar-bg       :background base3)
   (company-scrollbar-fg       :background green)
   (company-preview-common     :foreground green)
   (flycheck-error   :underline `(:style wave :color ,red)    :background base3)
   (flycheck-warning :underline `(:style wave :color ,yellow) :background base3)
   (flycheck-info    :underline `(:style wave :color ,blue)   :background base3)
   (dired-directory :foreground green :bold t)
   (dired-symlink   :foreground blue)
   (dired-ignored   :foreground base6)
   (dired-header    :foreground yellow :bold t)
   (dired-marked    :foreground yellow)
   (magit-section-heading             :foreground yellow :bold t)
   (magit-diff-hunk-heading           :background base3  :foreground fg-alt)
   (magit-diff-hunk-heading-highlight :background base4  :foreground fg)
   (magit-branch-local                :foreground green)
   (magit-branch-remote               :foreground blue)
   (magit-diff-added           :background (doom-blend green bg 0.15) :foreground (doom-lighten green 0.3))
   (magit-diff-added-highlight :background (doom-blend green bg 0.25) :foreground (doom-lighten green 0.15))
   (magit-diff-removed         :background (doom-blend red   bg 0.15) :foreground (doom-lighten red   0.3))
   (magit-diff-removed-highlight :background (doom-blend red bg 0.25) :foreground (doom-lighten red   0.15))
   ((org-level-1 &override) :foreground green   :bold t)
   ((org-level-2 &override) :foreground blue    :bold t)
   ((org-level-3 &override) :foreground yellow  :bold t)
   ((org-level-4 &override) :foreground magenta :bold t)
   ((org-code    &override) :foreground orange  :background base3)
   ((org-block   &override) :background base3)
   (org-link     :foreground blue   :underline t)
   (org-table    :foreground green)
   (org-verbatim :foreground yellow)
   (rainbow-delimiters-depth-1-face :foreground green)
   (rainbow-delimiters-depth-2-face :foreground blue)
   (rainbow-delimiters-depth-3-face :foreground yellow)
   (rainbow-delimiters-depth-4-face :foreground magenta)
   (which-key-key-face                 :foreground green)
   (which-key-command-description-face :foreground blue)
   (which-key-group-description-face   :foreground yellow))

  ())

;;; doom-delcx-teal-theme.el ends here
