;;; doom-delcx-parchment-theme.el --- Warm parchment light theme -*- lexical-binding: t; no-byte-compile: t; -*-
;;; Commentary: bg #EEE4D0  fg #383430  strings #8A6020  types #28689C  control #287858  numbers #884868
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-delcx-parchment
  "A warm light theme with the feel of aged parchment and manuscript ink."
  :family 'doom-delcx-parchment
  :background-mode 'light

  ;; name        gui           256           16
  ((bg          '("#EEE4D0"    "#EEE4D0"     nil))
   (bg-alt      '("#E4DAC6"    "#E4DAC6"     nil))
   (base0       '("#EEE4D0"    "#EEE4D0"     nil))
   (base1       '("#E4DAC6"    "#E4DAC6"     nil))
   (base2       '("#DAD0BC"    "#DAD0BC"     nil))
   (base3       '("#C8C0AE"    "#C8C0AE"     nil))
   (base4       '("#B0A898"    "#B0A898"     nil))
   (base5       '("#90887A"    "#90887A"     nil))
   (base6       '("#706860"    "#706860"     nil))
   (base7       '("#504844"    "#504844"     nil))
   (base8       '("#383430"    "#383430"     nil))
   (fg          '("#383430"    "#383430"     nil))
   (fg-alt      '("#504844"    "#504844"     nil))

   (grey        '("#90887A"    "#90887A"     nil))
   (red         '("#884868"    "#884868"     nil))
   (orange      '("#8A6020"    "#8A6020"     nil))
   (yellow      '("#8A6020"    "#8A6020"     nil))
   (dark-yellow '("#6A4810"    "#6A4810"     nil))
   (green       '("#287858"    "#287858"     nil))
   (dark-green  '("#186040"    "#186040"     nil))
   (teal        '("#287858"    "#287858"     nil))
   (blue        '("#28689C"    "#28689C"     nil))
   (dark-blue   '("#18507C"    "#18507C"     nil))
   (cyan        '("#287858"    "#287858"     nil))
   (dark-cyan   '("#186040"    "#186040"     nil))
   (magenta     '("#884868"    "#884868"     nil))
   (violet      '("#A06080"    "#A06080"     nil))

   (highlight      green)
   (vertical-bar   base3)
   (selection      base3)
   (builtin        blue)
   (comments       base5)
   (doc-comments   base5)
   (constants      magenta)
   (functions      fg)
   (keywords       green)
   (methods        fg)
   (operators      fg)
   (type           blue)
   (strings        orange)
   (variables      fg)
   (numbers        magenta)
   (region         base3)
   (error          red)
   (warning        yellow)
   (success        green)

   (vc-modified    (doom-darken blue  0.1))
   (vc-added       (doom-darken green 0.1))
   (vc-deleted     (doom-darken red   0.1))

   (modeline-bg            base2)
   (modeline-fg            fg)
   (modeline-inactive-bg   bg)
   (modeline-inactive-fg   base5))

  ((cursor :background "white")
   (hl-line :background base2)
   ((line-number &override)              :foreground base4)
   ((line-number-current-line &override) :background base2 :foreground fg)
   (isearch        :foreground base0 :background (doom-darken orange 0.3))
   (lazy-highlight :background base3 :foreground fg :bold bold)
   ((link &override) :foreground blue :underline t)
   (minibuffer-prompt :foreground green)
   (mode-line          :background base2 :foreground modeline-fg)
   (mode-line-inactive :background bg    :foreground modeline-inactive-fg)
   (show-paren-match :background base3 :foreground fg :bold t)
   (company-tooltip            :background base2 :foreground fg)
   (company-tooltip-selection  :background base3)
   (company-tooltip-common     :foreground green)
   (company-tooltip-annotation :foreground base5)
   (company-scrollbar-bg       :background base2)
   (company-scrollbar-fg       :background base3)
   (company-preview-common     :foreground green)
   (flycheck-error   :underline `(:style wave :color ,red)    :background base2)
   (flycheck-warning :underline `(:style wave :color ,yellow) :background base2)
   (flycheck-info    :underline `(:style wave :color ,blue)   :background base2)
   (dired-directory :foreground green :bold t)
   (dired-symlink   :foreground blue)
   (dired-ignored   :foreground base5)
   (dired-header    :foreground orange :bold t)
   (dired-marked    :foreground orange)
   (magit-section-heading             :foreground orange :bold t)
   (magit-diff-hunk-heading           :background base2  :foreground fg-alt)
   (magit-diff-hunk-heading-highlight :background base3  :foreground fg)
   (magit-branch-local                :foreground green)
   (magit-branch-remote               :foreground blue)
   (magit-diff-added           :background (doom-blend green bg 0.15) :foreground (doom-darken green 0.3))
   (magit-diff-added-highlight :background (doom-blend green bg 0.25) :foreground (doom-darken green 0.4))
   (magit-diff-removed         :background (doom-blend red   bg 0.15) :foreground (doom-darken red   0.3))
   (magit-diff-removed-highlight :background (doom-blend red bg 0.25) :foreground (doom-darken red   0.4))
   ((org-level-1 &override) :foreground green   :bold t)
   ((org-level-2 &override) :foreground blue    :bold t)
   ((org-level-3 &override) :foreground orange  :bold t)
   ((org-level-4 &override) :foreground magenta :bold t)
   ((org-code    &override) :foreground orange  :background base2)
   ((org-block   &override) :background base2)
   (org-link     :foreground blue   :underline t)
   (org-table    :foreground green)
   (org-verbatim :foreground orange)
   (rainbow-delimiters-depth-1-face :foreground green)
   (rainbow-delimiters-depth-2-face :foreground blue)
   (rainbow-delimiters-depth-3-face :foreground orange)
   (rainbow-delimiters-depth-4-face :foreground magenta)
   (which-key-key-face                 :foreground green)
   (which-key-command-description-face :foreground blue)
   (which-key-group-description-face   :foreground orange))

  ())

;;; doom-delcx-parchment-theme.el ends here
