;;; doom-delcx-amber-theme.el --- Warm amber phosphor terminal dark -*- lexical-binding: t; no-byte-compile: t; -*-
;;; Commentary: bg #1C1810  fg #CCC0A8  strings #D4A448  types #7E9CB8  control #60B8A0  numbers #B88090
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-delcx-amber
  "A warm dark theme evoking amber phosphor terminals."
  :family 'doom-delcx-amber
  :background-mode 'dark

  ;; name        gui           256           16
  ((bg          '("#1C1810"    "#1C1810"     nil))
   (bg-alt      '("#2B271F"    "#2B271F"     nil))
   (base0       '("#100E0A"    "#100E0A"     nil))
   (base1       '("#1C1810"    "#1C1810"     nil))
   (base2       '("#2B271F"    "#2B271F"     nil))
   (base3       '("#3D3931"    "#3D3931"     nil))
   (base4       '("#504B43"    "#504B43"     nil))
   (base5       '("#625D55"    "#625D55"     nil))
   (base6       '("#857E74"    "#857E74"     nil))
   (base7       '("#A89E90"    "#A89E90"     nil))
   (base8       '("#CCC0A8"    "#CCC0A8"     nil))
   (fg          '("#CCC0A8"    "#CCC0A8"     nil))
   (fg-alt      '("#A89E90"    "#A89E90"     nil))

   (grey        '("#857E74"    "#857E74"     nil))
   (red         '("#B88090"    "#B88090"     nil))
   (orange      '("#D4A448"    "#D4A448"     nil))
   (yellow      '("#D4A448"    "#D4A448"     nil))
   (dark-yellow '("#AA8238"    "#AA8238"     nil))
   (green       '("#60B8A0"    "#60B8A0"     nil))
   (dark-green  '("#429080"    "#429080"     nil))
   (teal        '("#60B8A0"    "#60B8A0"     nil))
   (blue        '("#7E9CB8"    "#7E9CB8"     nil))
   (dark-blue   '("#5E7C98"    "#5E7C98"     nil))
   (cyan        '("#60B8A0"    "#60B8A0"     nil))
   (dark-cyan   '("#429080"    "#429080"     nil))
   (magenta     '("#B88090"    "#B88090"     nil))
   (violet      '("#C890A0"    "#C890A0"     nil))

   (highlight      green)
   (vertical-bar   base4)
   (selection      base4)
   (builtin        blue)
   (comments       base6)
   (doc-comments   base6)
   (constants      magenta)
   (functions      fg)
   (keywords       green)
   (methods        fg)
   (operators      fg)
   (type           blue)
   (strings        orange)
   (variables      fg)
   (numbers        magenta)
   (region         base4)
   (error          red)
   (warning        yellow)
   (success        green)

   (vc-modified    (doom-darken blue  0.15))
   (vc-added       (doom-darken green 0.15))
   (vc-deleted     (doom-darken red   0.15))

   (modeline-bg            base3)
   (modeline-fg            fg)
   (modeline-inactive-bg   bg)
   (modeline-inactive-fg   base6))

  ((cursor :background "white")
   (hl-line :background base3)
   ((line-number &override)              :foreground base5)
   ((line-number-current-line &override) :background base3 :foreground yellow)
   (isearch        :foreground base0 :background orange)
   (lazy-highlight :background base4 :foreground fg :bold bold)
   ((link &override) :foreground blue :underline t)
   (minibuffer-prompt :foreground green)
   (mode-line          :background base3 :foreground modeline-fg)
   (mode-line-inactive :background bg    :foreground modeline-inactive-fg)
   (show-paren-match :background base4 :foreground fg :bold t)
   (company-tooltip            :background base3 :foreground fg)
   (company-tooltip-selection  :background base4)
   (company-tooltip-common     :foreground green)
   (company-tooltip-annotation :foreground base6)
   (company-scrollbar-bg       :background base3)
   (company-scrollbar-fg       :background green)
   (company-preview-common     :foreground green)
   (flycheck-error   :underline `(:style wave :color ,red)    :background base3)
   (flycheck-warning :underline `(:style wave :color ,yellow) :background base3)
   (flycheck-info    :underline `(:style wave :color ,blue)   :background base3)
   (dired-directory :foreground green :bold t)
   (dired-symlink   :foreground blue)
   (dired-ignored   :foreground base6)
   (dired-header    :foreground yellow :bold t)
   (dired-marked    :foreground yellow)
   (magit-section-heading             :foreground yellow :bold t)
   (magit-diff-hunk-heading           :background base3  :foreground fg-alt)
   (magit-diff-hunk-heading-highlight :background base4  :foreground fg)
   (magit-branch-local                :foreground green)
   (magit-branch-remote               :foreground blue)
   (magit-diff-added           :background (doom-blend green bg 0.15) :foreground (doom-lighten green 0.3))
   (magit-diff-added-highlight :background (doom-blend green bg 0.25) :foreground (doom-lighten green 0.15))
   (magit-diff-removed         :background (doom-blend red   bg 0.15) :foreground (doom-lighten red   0.3))
   (magit-diff-removed-highlight :background (doom-blend red bg 0.25) :foreground (doom-lighten red   0.15))
   ((org-level-1 &override) :foreground green   :bold t)
   ((org-level-2 &override) :foreground blue    :bold t)
   ((org-level-3 &override) :foreground yellow  :bold t)
   ((org-level-4 &override) :foreground magenta :bold t)
   ((org-code    &override) :foreground orange  :background base3)
   ((org-block   &override) :background base3)
   (org-link     :foreground blue   :underline t)
   (org-table    :foreground green)
   (org-verbatim :foreground yellow)
   (rainbow-delimiters-depth-1-face :foreground green)
   (rainbow-delimiters-depth-2-face :foreground blue)
   (rainbow-delimiters-depth-3-face :foreground yellow)
   (rainbow-delimiters-depth-4-face :foreground magenta)
   (which-key-key-face                 :foreground green)
   (which-key-command-description-face :foreground blue)
   (which-key-group-description-face   :foreground yellow))

  ())

;;; doom-delcx-amber-theme.el ends here
