;;; doom-delcx-dusk-theme.el --- Muted dusk dark theme -*- lexical-binding: t; no-byte-compile: t; -*-
;;; Commentary: bg #22201E  fg #CEC6B8  strings #C8A050  types #7898C0  control #58B0A0  numbers #C08898
;;; Code:
(require 'doom-themes)

(def-doom-theme doom-delcx-dusk
  "A muted dark theme in the colours of a fading dusk sky."
  :family 'doom-delcx-dusk
  :background-mode 'dark

  ;; name        gui           256           16
  ((bg          '("#22201E"    "#22201E"     nil))
   (bg-alt      '("#312F2D"    "#312F2D"     nil))
   (base0       '("#161412"    "#161412"     nil))
   (base1       '("#22201E"    "#22201E"     nil))
   (base2       '("#312F2D"    "#312F2D"     nil))
   (base3       '("#403E3C"    "#403E3C"     nil))
   (base4       '("#524F4D"    "#524F4D"     nil))
   (base5       '("#636160"    "#636160"     nil))
   (base6       '("#857E78"    "#857E78"     nil))
   (base7       '("#A8A098"    "#A8A098"     nil))
   (base8       '("#CEC6B8"    "#CEC6B8"     nil))
   (fg          '("#CEC6B8"    "#CEC6B8"     nil))
   (fg-alt      '("#A8A098"    "#A8A098"     nil))

   (grey        '("#857E78"    "#857E78"     nil))
   (red         '("#C08898"    "#C08898"     nil))
   (orange      '("#C8A050"    "#C8A050"     nil))
   (yellow      '("#C8A050"    "#C8A050"     nil))
   (dark-yellow '("#A08040"    "#A08040"     nil))
   (green       '("#58B0A0"    "#58B0A0"     nil))
   (dark-green  '("#408890"    "#408890"     nil))
   (teal        '("#58B0A0"    "#58B0A0"     nil))
   (blue        '("#7898C0"    "#7898C0"     nil))
   (dark-blue   '("#5878A0"    "#5878A0"     nil))
   (cyan        '("#58B0A0"    "#58B0A0"     nil))
   (dark-cyan   '("#408890"    "#408890"     nil))
   (magenta     '("#C08898"    "#C08898"     nil))
   (violet      '("#C8A0A8"    "#C8A0A8"     nil))

   (highlight      green)
   (vertical-bar   base4)
   (selection      base4)
   (builtin        blue)
   (comments       base6)
   (doc-comments   base6)
   (constants      magenta)
   (functions      fg)
   (keywords       green)
   (methods        fg)
   (operators      fg)
   (type           blue)
   (strings        orange)
   (variables      fg)
   (numbers        magenta)
   (region         base4)
   (error          red)
   (warning        yellow)
   (success        green)

   (vc-modified    (doom-darken blue  0.15))
   (vc-added       (doom-darken green 0.15))
   (vc-deleted     (doom-darken red   0.15))

   (modeline-bg            base3)
   (modeline-fg            fg)
   (modeline-inactive-bg   bg)
   (modeline-inactive-fg   base6))

  ((cursor :background "white")
   (hl-line :background base3)
   ((line-number &override)              :foreground base5)
   ((line-number-current-line &override) :background base3 :foreground yellow)
   (isearch        :foreground base0 :background orange)
   (lazy-highlight :background base4 :foreground fg :bold bold)
   ((link &override) :foreground blue :underline t)
   (minibuffer-prompt :foreground green)
   (mode-line          :background base3 :foreground modeline-fg)
   (mode-line-inactive :background bg    :foreground modeline-inactive-fg)
   (show-paren-match :background base4 :foreground fg :bold t)
   (company-tooltip            :background base3 :foreground fg)
   (company-tooltip-selection  :background base4)
   (company-tooltip-common     :foreground green)
   (company-tooltip-annotation :foreground base6)
   (company-scrollbar-bg       :background base3)
   (company-scrollbar-fg       :background green)
   (company-preview-common     :foreground green)
   (flycheck-error   :underline `(:style wave :color ,red)    :background base3)
   (flycheck-warning :underline `(:style wave :color ,yellow) :background base3)
   (flycheck-info    :underline `(:style wave :color ,blue)   :background base3)
   (dired-directory :foreground green :bold t)
   (dired-symlink   :foreground blue)
   (dired-ignored   :foreground base6)
   (dired-header    :foreground yellow :bold t)
   (dired-marked    :foreground yellow)
   (magit-section-heading             :foreground yellow :bold t)
   (magit-diff-hunk-heading           :background base3  :foreground fg-alt)
   (magit-diff-hunk-heading-highlight :background base4  :foreground fg)
   (magit-branch-local                :foreground green)
   (magit-branch-remote               :foreground blue)
   (magit-diff-added           :background (doom-blend green bg 0.15) :foreground (doom-lighten green 0.3))
   (magit-diff-added-highlight :background (doom-blend green bg 0.25) :foreground (doom-lighten green 0.15))
   (magit-diff-removed         :background (doom-blend red   bg 0.15) :foreground (doom-lighten red   0.3))
   (magit-diff-removed-highlight :background (doom-blend red bg 0.25) :foreground (doom-lighten red   0.15))
   ((org-level-1 &override) :foreground green   :bold t)
   ((org-level-2 &override) :foreground blue    :bold t)
   ((org-level-3 &override) :foreground yellow  :bold t)
   ((org-level-4 &override) :foreground magenta :bold t)
   ((org-code    &override) :foreground orange  :background base3)
   ((org-block   &override) :background base3)
   (org-link     :foreground blue   :underline t)
   (org-table    :foreground green)
   (org-verbatim :foreground yellow)
   (rainbow-delimiters-depth-1-face :foreground green)
   (rainbow-delimiters-depth-2-face :foreground blue)
   (rainbow-delimiters-depth-3-face :foreground yellow)
   (rainbow-delimiters-depth-4-face :foreground magenta)
   (which-key-key-face                 :foreground green)
   (which-key-command-description-face :foreground blue)
   (which-key-group-description-face   :foreground yellow))

  ())

;;; doom-delcx-dusk-theme.el ends here
